spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/hc-groovebom-test}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:root}
        driver-class-name: org.postgresql.Driver
    jpa:
        generate-ddl: true
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    error:
        include-stacktrace: never
token:
    secret: ${JWT_SECRET:root}
springdoc:
    swagger-ui:
        path: /



        
